___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [9]:
print(np.__version__)
print(np.__config__.show())

1.20.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


Створити вектор з 10 елементів, заповнений одиницями:

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Створити вектор із значеннями від 0 до 10:

In [16]:
np.arange(0,11,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створити матрицю 5 на 5, заповнену нулями:

In [19]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [48]:
z = np.random.randint(0,5,size=20)
z

array([2, 4, 0, 2, 1, 3, 3, 0, 3, 3, 0, 4, 2, 0, 4, 3, 2, 3, 3, 0])

In [50]:
[i for i in range(len(z)) if z[i]!=0]

[0, 1, 3, 4, 5, 6, 8, 9, 11, 12, 14, 15, 16, 17, 18]

Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [53]:
np.mean(z), np.median(z),np.std(z)

(2.1, 2.5, 1.4106735979665883)

Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [99]:
A = np.random.random([4,2])
B = np.random.random([2,2])

In [100]:
C = A@B
print(C)

[[0.41391206 0.13586614]
 [0.59574321 0.75127194]
 [0.39594941 0.04071948]
 [0.40458863 0.7181433 ]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [101]:
Cv = C.copy().reshape(8)
Cv_min = np.min(Cv)
Cv_max = np.max(Cv)
print(Cv_min, Cv_max)

0.04071948432713293 0.751271935514218


In [102]:
Cv

array([0.41391206, 0.13586614, 0.59574321, 0.75127194, 0.39594941,
       0.04071948, 0.40458863, 0.7181433 ])

In [103]:
for i in range(len(Cv)):
    if Cv[i]==Cv_max:
        Cv[i] = 0

In [104]:
Cv

array([0.41391206, 0.13586614, 0.59574321, 0.        , 0.39594941,
       0.04071948, 0.40458863, 0.7181433 ])

Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [123]:
np.correlate(C[0],C[1]), np.correlate(C[0],C[2]), np.correlate(C[0],C[3])

(array([0.34865772]), array([0.16942064]), array([0.26503547]))

Дано матрицю. Знайти ранг матриці:

In [124]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])

In [125]:
np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [126]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [129]:
cov = np.cov(a.T)

In [130]:
np.linalg.eigh(cov)

(array([2.40747601e-15, 1.04984277e+01, 6.35015723e+01]),
 array([[-4.47213595e-01,  7.94627466e-01, -4.10569349e-01],
        [-2.22044605e-16, -4.59030487e-01, -8.88420515e-01],
        [-8.94427191e-01, -3.97313733e-01,  2.05284674e-01]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [144]:
a = np.random.randint(0,10,50)

In [145]:
a

array([5, 0, 4, 3, 5, 6, 9, 0, 5, 6, 2, 5, 3, 6, 6, 6, 5, 8, 3, 5, 1, 4,
       5, 6, 7, 2, 0, 3, 7, 8, 8, 8, 0, 2, 7, 8, 1, 2, 8, 6, 6, 9, 8, 1,
       9, 7, 1, 4, 4, 8])

In [147]:
np.bincount(a).argmax()

6

Виведіть лише парні числа, що діляться на 5:

In [148]:
a = np.random.randint(0,10,50)

In [151]:
a

array([8, 4, 9, 6, 9, 6, 7, 6, 1, 1, 4, 4, 9, 6, 2, 3, 4, 4, 6, 5, 3, 5,
       0, 1, 4, 8, 2, 6, 2, 2, 8, 6, 1, 2, 6, 0, 6, 5, 8, 1, 1, 4, 2, 6,
       7, 7, 6, 9, 0, 1])

In [158]:
np.ma.where((a%2==0)&(a%5==0))

(array([22, 35, 48], dtype=int64),)

Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [159]:
a = [[2,5],
     [1,-10]]
b = [1,3]
np.linalg.solve(a,b)

array([ 1. , -0.2])